name: 04-Using Actions

on:
    push:

jobs:
    setup-node:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout Code
             uses: actions/checkout@v4

           - name: Setup Node
             uses: actions/setup-node@v4
             with:
               node-version: 23.6.1

           - name: install NPM Packages
             run: |
                cd 04-using-actions/react-app
                npm install
                
           - name: Run React App
             run: |
                npm run start

