name: 04-Using Actions

on:
    push:

jobs:
    setup-node:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout 
             uses: actions/checkout@v4
           - name: echo PWD
             run: pwd  
           - name: install NPM Packages
             run: |
                cd 04-using-actions/react-app
                npm install
           - name: Run App
             run: npm run start

