name: 04-Using Actions

on:
    push:

jobs:
    build:
        defaults:
          run:
            working-directory: 04-using-actions/angular-app

        runs-on: ubuntu-latest
        steps:
           - name: Checkout Code
             uses: actions/checkout@v4

           - name: Setup Node
             uses: actions/setup-node@v4
             with:
               node-version: 23.6.1

           - name: Install Angular CLI
             run: npm install -g @angular/cli

           - name: Run test
             run: ng test

