name: 06-Contexts
run-name: " || DEBUG: ${{inputs.debug}}"
env:
    WORKFLOW_ENV: "workflow"

on:
    workflow_dispatch: 
        inputs:
            debug: 
                type: boolean
                default: false
    push: 
        branches: 
            - main

jobs:
    echo-contexts:
        env: 
            Jobs_ENV: "Jobs ENV"

        runs-on: ubuntu-latest
        steps:
            - name: Echo gitthub Context
              run: |
                echo "Event: ${{github.event_name}}"
                echo "SHA: ${{github.sha}}"
                echo "Workflow: ${{github.workflow}}"
                echo "Run ID: ${{github.run_id}}"
                echo "Ref: ${{github.ref}}"
                echo "Run Number: ${{github.run_number}}"
            - name: Echo VARS Context
              run: |
                echo "Variable: ${{vars.MY_VAR}}"
                echo "ENV: ${{env.Jobs_ENV}}"
                
