name: 06-Contexts
run-name: "nun-name: ${{inputs.name}}"

on:
    workflow_dispatch: 
        inputs:
            name: 
                type: boolean
                default: false
    push: 
        branches: 
            - main

jobs:
    echo-contexts:
        runs-on: ubuntu-latest
        steps:
            - name: Echo gitthub Context
              run: |
                echo "Event: ${{github.event_name}}"
                echo "SHA: ${{github.sha}}"
                echo "Workflow: ${{github.workflow}}"
                echo "Run ID: ${{github.run_id}}"
                echo "Ref: ${{github.ref}}"
                echo "Run Number: ${{github.run_number}}"
            - name: Echo VARS Context
              run: |
                echo "Variable: ${{vars.MY_VAR}}"
                
