name: 07 - Using Expressions

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type:  boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              if: ${{inputs.debug == true}}
              run: |
                echo "Triggerd because debug is true"
                echo "Branch: ${{github.ref}}"
                echo "Branch Name: ${{github.ref_name}}"
                echo "Runner Arch: ${{runner.arch}}"
