name: 07-Using Expressions
run-name: 07 - Using Expressins ${{github.run_id}} - username ${{github.actor}}

on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type:  boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: echo if debug is true
              if: ${{inputs.debug == true}}
              run: |
                echo "Triggerd because debug is true"
                echo "Branch: ${{github.ref}}"
                echo "Branch Name: ${{github.ref_name}}"
                echo "Runner Arch: ${{runner.arch}}"
            - name: echo if debug is true and branch is main
              if: inputs.debug && github.ref_name == 'main'
              run: echo "Triggerd because debug is true and branch is main"
              
