name: 08-Using Variables
run-name: "08-Using Variables - username: ${{github.actor}}"

on:
    push:
    workflow_dispatch: 

env:
    WORKFLOW_ENV: "workflow varaible"

jobs:
    echo:
        env:
            JOB_VAR: "job varaible"
        runs-on: ubuntu-latest
        steps:
            - name: Print ENV variables
              env:
                STEP_VAR: "step varaible"
              run: |
                echo "work: ${{env.WORKFLOW_ENV}}"
                echo "job: ${{env.JOB_VAR}}"
                echo "step: ${{env.STEP_VAR}}"

